### ISSUE TITLE
Add/Delete items and section positions

### ISSUE THREAD

**Issue by davideas** [luizgrp/SectionedRecyclerViewAdapter#1]
Hello, what happens if we delete or add new items to the list/section, I mean how do we have the correct new positions of the sections?

**Comment by luizgrp** [comment]
Hi @davideas, 

I changed to public the methods [getSectionPosition](https://github.com/luizgrp/SectionedRecyclerViewAdapter/blob/master/library/src/main/java/io/github/luizgrp/sectionedrecyclerviewadapter/SectionedRecyclerViewAdapter.java#L296) and [getSectionForPosition](https://github.com/luizgrp/SectionedRecyclerViewAdapter/blob/master/library/src/main/java/io/github/luizgrp/sectionedrecyclerviewadapter/SectionedRecyclerViewAdapter.java#L268) of SectionedRecyclerViewAdapter, you can find an example of how to use them [here](https://github.com/luizgrp/SectionedRecyclerViewAdapter/blob/master/app/src/main/java/io/github/luizgrp/sectionedrecyclerviewadapter/demo/Example1Fragment.java#L94).

Let me know if that helps.

Library version has been updated to 1.0.2 including these changes.

Thanks!
