### ISSUE TITLE
Scrolling is jerky.

### ISSUE THREAD

**Issue by momersaleem-sdsol** [luizgrp/SectionedRecyclerViewAdapter#10]
I have added 4 sections and each section has around 4 to 5 items. When I scroll (up and down) list, it jerks. How can I make it scroll smoothly.

**Comment by luizgrp** [comment]
Could you please paste your code and the xml layouts?

**Comment by momersaleem-sdsol** [comment]
// section class
public class CategorySection extends StatelessSection {

    private OnCategoryItemSelectionListener onCategoryItemSelectionListener = null;

    Context context = null;
    private SectionedRecyclerViewAdapter sectionAdapter = null;
    String title;
    String description;
    List<Item> itemList;

    public CategorySection(Context context, SectionedRecyclerViewAdapter adapter,
                           String title, String description, List<Item> list) {
        super(R.layout.item_section_menu_header, R.layout.item_section_menu_item);

        this.context = context;
        sectionAdapter = adapter;
        this.title = title;
        this.description = description;
        this.itemList = list;
    }

    @Override
    public int getContentItemsTotal() {
        return itemList.size();
    }

    @Override
    public RecyclerView.ViewHolder getItemViewHolder(View view) {
        return new ItemViewHolder(view);
    }

    @Override
    public void onBindItemViewHolder(RecyclerView.ViewHolder holder, int position) {
        final ItemViewHolder itemHolder = (ItemViewHolder) holder;

        String price = itemList.get(position).getPrice();
        String imageUrl = itemList.get(position).getImage();
        String name = itemList.get(position).getName();

        if (!Validation.isEmptyOrNull(price))
            itemHolder.tvPackagePrice.setText(price);

        if (!Validation.isEmptyOrNull(imageUrl)) {
            Glide.with(context)
                    .load(imageUrl)
                    .placeholder(R.drawable.placeholder)
                    .into(itemHolder.ivPackageImage);
        }

        if (!Validation.isEmptyOrNull(name))
            itemHolder.tvPackageName.setText(name);

        itemHolder.rootView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (onCategoryItemSelectionListener != null)
                    onCategoryItemSelectionListener.onCategoryItemSelected(v,
                            sectionAdapter.getSectionPosition(itemHolder.getAdapterPosition()),
                            title);
            }
        });
    }

    @Override
    public RecyclerView.ViewHolder getHeaderViewHolder(View view) {
        return new HeaderViewHolder(view);
    }

    @Override
    public void onBindHeaderViewHolder(RecyclerView.ViewHolder holder) {
        HeaderViewHolder headerHolder = (HeaderViewHolder) holder;

        headerHolder.tvMenuName.setText(title);

        if (!Validation.isEmptyOrNull(description)) {
            headerHolder.tvMenuDescription.setVisibility(View.VISIBLE);
            headerHolder.tvMenuDescription.setText(description);
        } else {
            headerHolder.tvMenuDescription.setVisibility(View.GONE);
        }
    }

    public interface OnCategoryItemSelectionListener {
        void onCategoryItemSelected(View view, int position, String categoryTitle);
    }

    public OnCategoryItemSelectionListener getOnCategoryItemSelectionListener() {
        return onCategoryItemSelectionListener;
    }

    public void setOnCategoryItemSelectionListener(OnCategoryItemSelectionListener onCategoryItemSelectionListener) {
        this.onCategoryItemSelectionListener = onCategoryItemSelectionListener;
    }

    public void addItems(List<Item> itemList) {
        if (this.itemList != null)
            this.itemList.addAll(itemList);
    }
}

// function for adding sections
private void initializeAdapterView() {

        SectionedRecyclerViewAdapter sectionAdapter = new SectionedRecyclerViewAdapter();

        for (final MenuItem menuItem : menuItemList) {

            CategorySection categorySection = new CategorySection(getLocalContext(),
                    sectionAdapter,
                    menuItem.getMenuName(),
                    menuItem.getMenuDescription(),
                    menuItem.getItems());

            sectionAdapter.addSection(categorySection);
        }

        final GridLayoutManager glm = new GridLayoutManager(getContext(), 2);
        glm.setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {
            @Override
            public int getSpanSize(int position) {
                switch (sectionAdapter.getSectionItemViewType(position)) {
                    case SectionedRecyclerViewAdapter.VIEW_TYPE_HEADER:
                        return 2;
                    default:
                        return 1;
                }
            }
        });

        rvMenuItems.setLayoutManager(glm);
        rvMenuItems.setAdapter(sectionAdapter);
}

// item_section_menu_header.xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_marginTop="@dimen/dp10"
    android:orientation="vertical">

    <com.sdsol.corporatecaterers.views.LatoRegularTextView
        android:id="@+id/tvMenuName"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="Graduation"
        android:textColor="@color/blue"
        android:textSize="@dimen/sp25" />

    <com.sdsol.corporatecaterers.views.LatoRegularTextView
        android:id="@+id/tvMenuDescription"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="Packages ser up to 30 guests"
        android:textColor="@color/blue"
        android:textSize="@dimen/sp16" />
</LinearLayout>

// item_section_menu_item.xml
<?xml version="1.0" encoding="utf-8"?>
<android.support.v7.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:card_view="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/rootView"
    android:layout_width="match_parent"
    android:layout_height="@dimen/menu_item_height"
    android:clickable="true"
    android:foreground="?android:attr/selectableItemBackground"
    card_view:cardCornerRadius="3dp"
    card_view:cardElevation="4dp"
    card_view:cardPreventCornerOverlap="true"
    card_view:cardUseCompatPadding="true">

    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <ImageView
            android:id="@+id/ivPackageImage"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:src="@drawable/placeholder" />

        <com.sdsol.corporatecaterers.views.LatoRegularTextView
            android:id="@+id/tvPackagePrice"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignParentRight="true"
            android:background="#55000000"
            android:padding="@dimen/dp5"
            android:text="$499.00/Package"
            android:textColor="@color/white"
            android:textSize="@dimen/sp16" />

        <com.sdsol.corporatecaterers.views.LatoRegularTextView
            android:id="@+id/tvPackageName"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_alignParentBottom="true"
            android:background="@color/blue"
            android:ellipsize="end"
            android:padding="@dimen/dp10"
            android:singleLine="true"
            android:text="$499.00/Package"
            android:textColor="@color/white"
            android:textSize="@dimen/sp14" />

    </RelativeLayout>

</android.support.v7.widget.CardView>

**Comment by luizgrp** [comment]
Could you please replace all your com.sdsol.corporatecaterers.views.LatoRegularTextView components by a normal TextView and test the scroll?

**Comment by momersaleem-sdsol** [comment]
It worked. Thanks.

**Comment by luizgrp** [comment]
Glad to hear that it worked.
Please ask your question in stackoverflow.com and more people will be able to help you.
