### ISSUE TITLE
Add onBind*ViewHolder methods with payloads parameter

### ISSUE THREAD

**Issue by luizgrp** [luizgrp/SectionedRecyclerViewAdapter#100]
- [x] I understand that if I don't use one of the following templates the issue will be closed and marked as invalid.

#### Use Case
Add [onBind*ViewHolder][1] methods with payloads parameter to Section and StatelessSection classes so it can be handled appropriately when the [notify][2] methods with payload parameter are called.

#### Design

- In SectionedRecyclerViewAdapter:

Override onBindViewHolder(RecyclerView.ViewHolder holder, int position, List<Object> payloads) to call onBind*ViewHolder with the payloads parameter, reusing the code from onBindViewHolder(RecyclerView.ViewHolder holder, int position).
It should call super if payloads is empty. References: this message from [Yigit][3] in this [article][4]. Examples [here][5] and [here][6].

- In Section and StatelessSection:

  - For every onBind*ViewHolder method, add a correspondent one with the payloads parameter;
  - Make onBindItemViewHolder(RecyclerView.ViewHolder holder, int position) non abstract.

- Add unit tests.

- Add sample in demo app.

#### How to use
Same usage as normal [notify*][2] and [onBindViewHolder][1] methods with payload as parameter from RecyclerView.Adapter.

  [1]: https://developer.android.com/reference/android/support/v7/widget/RecyclerView.Adapter.html#onBindViewHolder(VH,%20int,%20java.util.List<java.lang.Object>)
  [2]: https://developer.android.com/reference/android/support/v7/widget/RecyclerView.Adapter.html#notifyItemChanged(int,%20java.lang.Object)
  [3]: https://medium.com/@yigit/when-payloads-is-empty-onbindviewholder-should-not-return-but-instead-call-the-other-onbind-method-3cfccbf9e30
  [4]: https://proandroiddev.com/diffutil-is-a-must-797502bc1149
  [5]: https://medium.com/mindorks/diffutils-improving-performance-of-recyclerview-102b254a9e4a
  [6]: https://therubberduckdev.wordpress.com/2017/11/09/handle-data-change-in-recyclerview-using-diffutil/

**Comment by yccheok** [comment]
Hi,

This is my changes to support payloads, in our own project.

https://github.com/yccheok/SectionedRecyclerViewAdapter/commit/f7a4f96d22d2741b4a3655016f987eafd2a78f09

If you like the changes, feel free to let me know. I will perform some cleanup and unit test, to full-fill your project requirement.

Thank you.

**Comment by luizgrp** [comment]
Nice one @yccheok!
Please open a PR to merge against `develop` branch whenever you can!

**Comment by yccheok** [comment]
Hi @luizgrp 

I once release it as 0.2 in my own fork. Later, I discover the use case isn't strong, and in fact I don't really need that feature to achieve my desired outcome (Now, I can't remember what is my initial desired outcome)

Is there any other users request for such feature? If not, I think we can just ignore this pull request regarding payload, since there isn't a strong use case for it.

**Comment by luizgrp** [comment]
Well, first it would be nice to expose all the capabilities of the RecyclerView and not limit them.
I think this [article](https://medium.com/livefront/recyclerview-trick-selectively-bind-viewholders-with-payloads-4b28e3d2cce8) has a good use case. What do you think?

**Comment by yccheok** [comment]
Fair enough. I can do it when I'm free.

Gustavo Pagani <notifications@github.com> 於 2018年7月24日 週二 下午4:11 寫道：

**Comment by luizgrp** [comment]
Done in #180
