### ISSUE TITLE
Is synchronized (sections) required in getCopyOfSectionsMap

### ISSUE THREAD

**Issue by yccheok** [luizgrp/SectionedRecyclerViewAdapter#104]
https://github.com/luizgrp/SectionedRecyclerViewAdapter/blob/1f248435ea09561c42afabf492adb427e2ab626e/library/src/main/java/io/github/luizgrp/sectionedrecyclerviewadapter/SectionedRecyclerViewAdapter.java#L519

Is `synchronized (sections) {` required, as it seems like unable to prevent `java.util.ConcurrentModificationException`, if user is calling `getCopyOfSectionsMap` from a non-UI thread.

I don't think it is a bad thing, if such exception is being thrown if user is calling `getCopyOfSectionsMap` from a non-UI thread.

**Comment by luizgrp** [comment]
Hi @yccheok! 
The intention of having the synchronized in this method is to avoid items being added to the map while the copy is being made. Do you think the responsibility of locking it should be of the user of lib?

**Comment by yccheok** [comment]
Hi @luizgrp 

Yes. All the time, my view on this library is that, it shouldn't have any knowledge on threading. Hence, seeing `synchronized` keyword in the code, seem a bit awkward to me :)

I believe you had achieve goal of `SectionedRecyclerViewAdapter` - provides section liked UI effect for RecyclerView. For threading issues, it should be the responsible of another library, or another class, or responsible of developers themselves.

**Comment by luizgrp** [comment]
Cool, I agree with you on this, will change it!
