### ISSUE TITLE
i use this great library, but i have an issue, i want to check all checkboxes of all sections on the recycelerview

### ISSUE THREAD

**Issue by moud-fadel** [luizgrp/SectionedRecyclerViewAdapter#107]
- [ ] I understand that if I don't use one of the following templates the issue will be closed and marked as invalid.

Please select one of the following templates accordingly and remove the others: 

### ISSUE TEMPLATE

- [ ] I have verified there are no duplicate active or recent issues.
- [ ] I have verified that I am using the latest version of SectionedRecyclerViewAdapter: `0.x.x`
- [ ] I have given my issue a non-generic title.

###### Expected behaviour
Describe what you expected to happen.

###### Actual behaviour
Describe what actually happened. Include the full traceback if there was an exception.

###### MCVE
Please include a [minimal, complete, and verifiable example](https://stackoverflow.com/help/mcve)(MCVE) to help us identify the issue. This also helps check that the issue is not with your own code. The MCVE can be one of the following:
- Unit tests with the scenario where the issue happens;
- Modified [demo app](https://github.com/luizgrp/SectionedRecyclerViewAdapter/tree/918337f66321055c7621377e5f5254b9b8078e4c/app) with the scenario where the issue happens - please also provide the reproduction steps;
- Your own code including layouts;
- [ ] Link to the MCVE code/project: `https://github.com/xxx/xxx`

### QUESTION TEMPLATE
- [ ] I have read over the documentation, checked out the examples and the demo app.
- [ ] I have given my issue a non-generic title.
- [ ] I understand that if I ask the same question in [stackoverflow](http://www.stackoverflow.com) website I will get answers way faster as more people will try to answer it.
- [ ] I understand that if I don't show a minimum effort of what I have tried and where I got stuck the question will be closed and marked as invalid.
- [ ] I have read the article [How do I ask a good question?](https://stackoverflow.com/help/how-to-ask)
- [ ] I understand that this library is a custom [Adapter](https://developer.android.com/reference/android/support/v7/widget/RecyclerView.Adapter.html) and **NOT** a custom [RecyclerView](https://developer.android.com/reference/android/support/v7/widget/RecyclerView.html). I understand the difference between them and what is possible to be done in an Adapter but not in a RecyclerView.

`YOUR QUESTION HERE`

### PR TEMPLATE
Please read [CONTRIBUTING](https://github.com/luizgrp/SectionedRecyclerViewAdapter/blob/master/CONTRIBUTING.md).

**Comment by luizgrp** [comment]
closing as it's not using any template
