### ISSUE TITLE
Can we have isHeaderPositionInSection and isFooterPositionInSection in SectionedRecyclerViewAdapter

### ISSUE THREAD

**Issue by yccheok** [luizgrp/SectionedRecyclerViewAdapter#109]
In conjunction with https://github.com/luizgrp/SectionedRecyclerViewAdapter/issues/108 , given an absolute position in RecyclerViewAdapter, we would like to know whether the absolute position is referring to header/footer of a Section.

Can we provide the following 2 functions - `isHeaderPositionInSection` and `isFooterPositionInSection`?

My first thought of their implementations would be

    public boolean isHeaderPositionInSection(int position) {
        return getPositionInSection(position) == -1;
    }

    public boolean isFooterPositionInSection(int position) {
        Section section = getSectionForPosition(position);
        
        if (!section.hasFooter()) {
            return false;
        }
        
        return getPositionInSection(position) == section.getSectionItemsTotal() - 1;
    }

**Comment by luizgrp** [comment]
Hi @yccheok,

I think these methods are redundant, given you can use `getSectionItemViewType(position)` and check if the value is `VIEW_TYPE_HEADER` or `VIEW_TYPE_FOOTER`.

What do you think?

**Comment by yccheok** [comment]
You are right. I re-check my application code again. I don't find a valid use case anymore for my previous request.
