### ISSUE TITLE
An Error message

### ISSUE THREAD

**Issue by shihabmi7** [luizgrp/SectionedRecyclerViewAdapter#11]
after implementing stateless section header;

```
E/RecyclerView: No adapter attached; skipping layout
                                                                     
  [ 08-03 06:15:12.708    82:   82 D/         ]
   Socket deconnection
```
Why showing this?

**Comment by luizgrp** [comment]
Hi @shihabmi7, have you tried the solution from the link below? 
http://stackoverflow.com/questions/29141729/recyclerview-no-adapter-attached-skipping-layout

**Comment by luizgrp** [comment]
http://stackoverflow.com/questions/37280134/android-studio-2-0-logcat-spammed-by-deconnection
