### ISSUE TITLE
Can we have getItemViewTypeInSection

### ISSUE THREAD

**Issue by yccheok** [luizgrp/SectionedRecyclerViewAdapter#110]
Currently, in `SectionedRecyclerViewAdapter`, we already have

    @Override
    public int getItemViewType(int position)

I was wondering, can we have something like

    public static int getItemViewTypeInSection(int itemViewType) {
        return itemViewType % VIEW_TYPE_QTY
    }

One of the use case is during drag-n-move, in `ItemTouchHelper.Callback` (I don't want to drag-n-move non loaded item), instead of writing

    @Override
    public int getMovementFlags(RecyclerView recyclerView, RecyclerView.ViewHolder viewHolder) {
        if (SectionedRecyclerViewAdapter.VIEW_TYPE_ITEM_LOADED != (viewHolder.getItemViewType() % Utils.VIEW_TYPE_QTY)) {
            final int dragFlags = 0;
            final int swipeFlags = 0;
            return makeMovementFlags(dragFlags, swipeFlags);
        }

I can write as

    @Override
    public int getMovementFlags(RecyclerView recyclerView, RecyclerView.ViewHolder viewHolder) {
        if (SectionedRecyclerViewAdapter.VIEW_TYPE_ITEM_LOADED != SectionedRecyclerViewAdapter.getItemViewTypeInSection(viewHolder.getItemViewType())) {
            final int dragFlags = 0;
            final int swipeFlags = 0;
            return makeMovementFlags(dragFlags, swipeFlags);
        }

https://github.com/yccheok/SectionedRecyclerViewAdapter/commit/ee1e4bfccbff7a60bbda51cb6541b1c3f220835e

**Comment by luizgrp** [comment]
Hi @yccheok,

We already have a method `getSectionItemViewType(position)` which does exactly what you are suggesting.

Let me know if you were thinking in something else.

**Comment by yccheok** [comment]
@luizgrp 

Done. Hope you like my change.

https://github.com/luizgrp/SectionedRecyclerViewAdapter/pull/129

**Comment by luizgrp** [comment]
Closing as it's currently in develop.
