### ISSUE TITLE
Section expanding animations

### ISSUE THREAD

**Issue by SillybobXD** [luizgrp/SectionedRecyclerViewAdapter#114]
`How can I add an animation when a section is expanded?`
I want it to be so when I click the header then the items will scroll down while pushing the rest of the views.

Is it possible with your library? couldn't find anything of the sorts in the docs and examples.

**Comment by luizgrp** [comment]
Closing issue as it's not following any of the issues templates; Please use [Stackoverflow](https://stackoverflow.com/questions/tagged/sectionedrecyclerviewadapter).
