### ISSUE TITLE
How to detele the entire section

### ISSUE THREAD

**Issue by hafiz013** [luizgrp/SectionedRecyclerViewAdapter#117]
Hi, may I know how to delete the entire section let say for example section A contains header and list and section B as well. So how to delete section A?

**Comment by luizgrp** [comment]
Closing issue as it's not following any of the issues templates; Please use [Stackoverflow](https://stackoverflow.com/questions/tagged/sectionedrecyclerviewadapter).
The demo app has the functionality described in the Animations example.
