### ISSUE TITLE
How to make only one section expandable reccyclerview to open at a time ?

### ISSUE THREAD

**Issue by YogeshLegendkiller** [luizgrp/SectionedRecyclerViewAdapter#119]
First i must thank you for making such a wonderful library , am using expandable section adapter how to make it open only one at a time like if any section is open it must close if new one is open how to make it is it possible to do so ?

**Comment by davinh2306** [comment]
Override onParentListItemExpanded in your Adapter and collapse parent items which are opened

**Comment by luizgrp** [comment]
Glad that you are enjoying using the library!

Closing issue as it's not following any of the issues templates; Please use [Stackoverflow](https://stackoverflow.com/questions/tagged/sectionedrecyclerviewadapter)

**Comment by dharmikpadvsysunlimited** [comment]
Is it still opened? @luizgrp I did not find any question on StackOverflow.

**Comment by luizgrp** [comment]
@dharmikpadvsysunlimited what have you tried? where did you get stuck?

**Comment by wifirevaithi** [comment]
hi, i need a same feature can anyone help me????need to expand only one item at a time

**Comment by luizgrp** [comment]
@wifirevaithi what have you tried and where did you get stuck?

**Comment by wifirevaithi** [comment]
just setExpanded(false) in onBindItemViewHolder and it shows error when scrolling...i'm new to android development..please help me

**Comment by luizgrp** [comment]
@wifirevaithi please use stackoverflow.com for your questions, try to narrow it down into smaller problems, please read this [guide](https://stackoverflow.com/help/how-to-ask) first
