### ISSUE TITLE
NoClassDefFoundError after adding the library

### ISSUE THREAD

**Issue by felipedamiani** [luizgrp/SectionedRecyclerViewAdapter#12]
I had a "Caused by: java.lang.NoClassDefFoundError: android.support.design.internal.NavigationMenuPresenter" after adding the lib "compile 'io.github.luizgrp.sectionedrecyclerviewadapter:sectionedrecyclerviewadapter:1.0.4'"

Is it a known issue?

**Comment by luizgrp** [comment]
Hi @felipedamiani,

No, it is not a known issue.
I would suggest trying to run the (demo app)[https://github.com/luizgrp/SectionedRecyclerViewAdapter/blob/master/app] in your machine, then add the other dependencies of project to the demo app, one by one, until you find any conflicts.

Cheers

**Comment by felipedamiani** [comment]
Thanks for the answer @luizgrp, I did it and figured out the problem!
My project uses the support library 23.0.1 and yours 23.1.1 (incompatible with other libraries in my project). I just changed the versions and solved the problem.
