### ISSUE TITLE
Can we have notifyItemChangedInSection(Section)

### ISSUE THREAD

**Issue by yccheok** [luizgrp/SectionedRecyclerViewAdapter#124]
Is it possible that we can have

    notifyItemChangedInSection(Section)

Internally, it will be translated to

    notifyItemRangeChangedInSection(section, 0, section.getContentItemsTotal());

Thank you.

**Comment by luizgrp** [comment]
Sounds good 👍  maybe `notifyAllItemsChangedInSection`?
