### ISSUE TITLE
Help me !

### ISSUE THREAD

**Issue by trantientruong116** [luizgrp/SectionedRecyclerViewAdapter#127]
How to drag and swap item from one section to another section?

**Comment by Dreamersoul** [comment]
I would love to help but I am neither a maintainer nor a contributor to this project. Also you have two issues with the same idea. Please delete one and edit the other one to include all the information you need
Please don't mention random people in an issue cause I highly doubt that would help.

Check this out and try to make the same thing work for this library
[Link](http://android-er.blogspot.com/2015/01/drag-and-drop-items-between-listview_13.html?m=1)

**Comment by luizgrp** [comment]
#126
