### ISSUE TITLE
Hide empty headers

### ISSUE THREAD

**Issue by nugemon** [luizgrp/SectionedRecyclerViewAdapter#130]
Hello,

Great library and I've got it working.

I'd like to know if there is any way to hide empty sections when using Filter().
I have so many categories in my application and when filtering with a SearchView I still need to scroll down since it is still showing all the headers.

I tried hiding the header from onBindHeaderViewHolder with:
if(sectionItemsTotal == 1){
     headerHolder.headerView.setVisibility(View.GONE);
}
It does hide the view, but leave an empty spot on the list so effectively the same result as showing the header.

**Comment by nugemon** [comment]
I was able to find out what I did wrong, sorry for opening this issue.
Closing this

**Comment by Fahad-pnw** [comment]
could you guide how this was fixed?
