### ISSUE TITLE
AndroidX refactoring

### ISSUE THREAD

**Issue by Te-Z** [luizgrp/SectionedRecyclerViewAdapter#134]
Hi,

I have done a migration to androidx on one of my projects, and this invalidate all supports libraries from android. (documentation https://android-developers.googleblog.com/2018/05/hello-world-androidx.html )
This include recyclerview, annotations and so on. To change this I just had to replace all android.support imports with androidx. There's nothing else to change.

It's my first pull request ever so if I missed something or if you need more informations, feel free to ask me :)

[sectionedrecyclerviewadapter_androidx.zip](https://github.com/luizgrp/SectionedRecyclerViewAdapter/files/2396183/sectionedrecyclerviewadapter_androidx.zip)

**Comment by timc-mediamonks** [comment]
This is not a pull request 🤔

**Comment by matthewkrueger** [comment]
Would love to see this library get updated to androidx. I recently converted my project and while it still works, Android Studio complains about any subclasses I've made that override methods from this library.

**Comment by luizgrp** [comment]
Hi @Te-Z, thanks for your help. This is not a pull request, [here](https://help.github.com/articles/creating-a-pull-request/) you can find how to create one.

Meanwhile someone else already submitted a pull request with the changes to androidx and it has been merged into develop already 👍

**Comment by DannyS86** [comment]
When does a AndroidX-compatible library release? Can't add a dependency for the develop-branch, or how does it work?
Thank you very much!

**Comment by luizgrp** [comment]
Published as 2.0.0: https://github.com/luizgrp/SectionedRecyclerViewAdapter/pull/150
