### ISSUE TITLE
How to close a session in Expandable Session

### ISSUE THREAD

**Issue by Punamasawa** [luizgrp/SectionedRecyclerViewAdapter#135]
How to close a session in Expandable Session

**Comment by luizgrp** [comment]
you can also find the solution in [example 4](https://github.com/luizgrp/SectionedRecyclerViewAdapter/blob/5c8421ea7d1e539c7a4630a06a6228904c540674/app/src/main/java/io/github/luizgrp/sectionedrecyclerviewadapter/demo/Example4Fragment.java)
