### ISSUE TITLE
Dont Need the header 

### ISSUE THREAD

**Issue by ayubbaba** [luizgrp/SectionedRecyclerViewAdapter#139]
Hi Sir,

Sometimes I don't need the header in the section recycler view I am able to hide the title view using the visibility GONE but space is still occupied in the view is there any method to achieve these types

**Comment by yccheok** [comment]
I believe you are changing view visibility in `onBindHeaderViewHolder`. Don't do it there. It is not efficient.

A proper way is to call `setHasHeader(false)` of `Section`.
