### ISSUE TITLE
Example Sections + SearchView (Problem)

### ISSUE THREAD

**Issue by agueroveraalvaro** [luizgrp/SectionedRecyclerViewAdapter#148]
**Describe the bug**
I loose a few hours searching why sections + searchview is not working. Please change 
`filteredList.clear();`
for this
`this.filteredList=new ArrayList<>();`

**Additional context**
Soo many thanks for the library, thank soo much! it's great

**Comment by luizgrp** [comment]
Hi @agueroveraalvaro, thanks for reporting it. I can reproduce the issue, the SearchView with Sections example seems to be working fine?
