### ISSUE TITLE
Is it possible to make click in headerview 

### ISSUE THREAD

**Issue by yoganlegendkiller** [luizgrp/SectionedRecyclerViewAdapter#15]
Am using you library it awesome is it possible to make click in headerview like onclick in headerview

**Comment by luizgrp** [comment]
Hi, thanks! Yes it is possible, please see this [example](https://github.com/luizgrp/SectionedRecyclerViewAdapter/blob/master/app/src/main/java/io/github/luizgrp/sectionedrecyclerviewadapter/demo/Example5Fragment.java#L151).
