### ISSUE TITLE
Can we have a getSectionCount() function, and getSection(int index) function in SectionedRecyclerViewAdapter

### ISSUE THREAD

**Issue by yccheok** [luizgrp/SectionedRecyclerViewAdapter#152]
**Is your feature request related to a problem? Please describe.**
Sometimes, number of Sections can changed dynamically, and we need to get Nth Section, to turn on and turn off header. Instead of keeping separate List of Section within the app, it is better if we can get such information directly from `SectionedRecyclerViewAdapter`

**Describe the solution you'd like**
Provide a `getSectionCount()` function, and `getSection(int index)` function in `SectionedRecyclerViewAdapter`

**Describe alternatives you've considered**

**Additional context**
Currently, `Map<String, Section> sections` is being used in `SectionedRecyclerViewAdapter`. Not sure we need an additional `List<Section> sectionList` to serve the above purpose.

- [X] I understand that this library is a custom [Adapter](https://developer.android.com/reference/android/support/v7/widget/RecyclerView.Adapter.html) and **NOT** a custom [RecyclerView](https://developer.android.com/reference/android/support/v7/widget/RecyclerView.html). I understand the difference between them and what is possible to be done in an Adapter but not in a RecyclerView.

**Comment by luizgrp** [comment]
Hi @yccheok, the current alternative to `getSectionCount()` is `getCopyOfSectionsMap().size()` but yes, let's add a `getSectionCount()` with an implementation of `sections.size()`.

Regarding `getSection(index)`, it's a little more complex as sections is currently a LinkedHashMap and it does [not track index position](https://stackoverflow.com/a/10387318/1401164). I would look for alternatives from [Guava](https://github.com/google/guava/wiki/NewCollectionTypesExplained) or [Apache Commons](https://commons.apache.org/proper/commons-collections/).

**Comment by luizgrp** [comment]
Also there is this solution in #28 that I never had time to have a proper look at.
Not sure it would be good to have the index in the Section class as proposed there, it would get out of sync if the Section index gets changed and the adapter is not notified.
