### ISSUE TITLE
Is it possible we can have addSection by index?

### ISSUE THREAD

**Issue by yccheok** [luizgrp/SectionedRecyclerViewAdapter#154]
I was wondering, is it possible to have `addSection` by index feature?

The use case is following

```
// Initialization
adapter.addSection(paddingSection);
adapter.addSection(paddingSection);

```
...

```
// In the middle of execution, I would like to have noteSection between the 2 paddingSection
adapter.addSection(1, noteSection);
```

Is this feature request feasible?

Thanks.

**Comment by luizgrp** [comment]
This relates to #152: we would have to change the the type of sections from LinkedHashMap to a LinkedList and see if it doesn't break any other functionality.
