### ISSUE TITLE
how to reuse same viewholder in different section

### ISSUE THREAD

**Issue by scau-beyondboy** [luizgrp/SectionedRecyclerViewAdapter#155]
hi,i think add many the same sections by SectionedRecyclerViewAdapter, but i found it is easy to cause memory surge. i look check the souce code of this library, i found it didn't really reuse the same viewholder in different sections,because it returns different value for each item by getItemViewType(). so if i want to resue  same viewholder in different section, how can i do that?

**Comment by luizgrp** [comment]
Hey, at the moment there is no way of doing that, but I'm happy to discuss how to improve it if anyone is interested in implement it.
