### ISSUE TITLE
removeAllSections doesn't clear sectionViewTypeNumbers

### ISSUE THREAD

**Issue by Fintasys** [luizgrp/SectionedRecyclerViewAdapter#169]
When I looked over your code I realized that 
`removeSection` remove its Tag from `sectionViewTypeNumbers` but `removeAllSections` doesn't. 

Not a big thing but still wanted to let you know.

**Comment by luizgrp** [comment]
@Fintasys thanks for reporting it 👍

**Comment by Ryanhustler420** [comment]
> When I looked over your code I realized that
> `removeSection` remove its Tag from `sectionViewTypeNumbers` but `removeAllSections` doesn't.
> 
> Not a big thing but still wanted to let you know.

I faced the same issue. i used `sectionedRecyclerViewAdapter.notifyDataSetChanged();` and i worked!

**Comment by luizgrp** [comment]
Addressed [here](https://github.com/luizgrp/SectionedRecyclerViewAdapter/pull/175/files#diff-5cdcd5419131d0531d7730fbec3fff97R294).
