### ISSUE TITLE
Why is gradle complaining about not finding appcompat-v7.jar?

### ISSUE THREAD

**Issue by lucas-dev** [luizgrp/SectionedRecyclerViewAdapter#17]
so I'm adding the library as a depency like this:

```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:24.1.1'
    compile 'com.android.support:design:24.1.1'
    ...
    compile 'io.github.luizgrp.sectionedrecyclerviewadapter:sectionedrecyclerviewadapter:1.0.4'
}

```

But when trying to sync the project with Gradle, I get this:

```
Warning:Module 'com.android.support:appcompat-v7:24.1.1' depends on one or more Android Libraries but is a jar
Error:A problem occurred configuring project ':app'.
> Could not find appcompat-v7.jar (com.android.support:appcompat-v7:24.1.1).
  Searched in the following locations:
      https://jcenter.bintray.com/com/android/support/appcompat-v7/24.1.1/appcompat-v7-24.1.1.jar

```

I know that the problem is caused by the library, because when I delete that line the project syncs successfully.

This is the full app/build.gradle file:

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 24
    buildToolsVersion "24.0.1"

    defaultConfig {
        applicationId "com.boel.demorv"
        minSdkVersion 15
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:24.1.1'
    compile 'com.android.support:design:24.1.1'
    compile 'com.android.support:cardview-v7:24.1.1'
    compile 'com.google.code.gson:gson:2.7'
    compile 'com.google.android.gms:play-services-maps:9.4.0'
    compile 'io.github.luizgrp.sectionedrecyclerviewadapter:sectionedrecyclerviewadapter:1.0.4'
}
```

So, why is gradle complaining about not finding appcompat-v7.jar in https://jcenter.bintray.com/com/android/support/appcompat-v7/24.1.1/appcompat-v7-24.1.1.jar?

Thanks in advance! I really want to use this library.

**Comment by luizgrp** [comment]
Hi, sorry for the delay in replying, has it been fixed?
I updated all the dependencies of the [example](https://github.com/luizgrp/SectionedRecyclerViewAdapter/tree/master/app) project in my local machine and it's working fine. Could you please try with the app project and see if you get the same error?

**Comment by lucas-dev** [comment]
thanks for the answer! I fixed the problem by manually adding the library files to my project. 
If I try to add the library with gradle, as shown in the sample code, I still get the error.
I was suggested to update the Support Library to the latest version, but these days I'm not having access to an internet connection capable of downloading large software updates.
Do you think that updating the Support Library would fix the problem? And if so, why is that the solution?
Sorry but I can't test that possible solution right now :(

**Comment by luizgrp** [comment]
No problem! I don't think updating the support library will fix the problem, the example project is working fine with support library 23.1.1.

Try adding the dependency like this:
```
compile ('io.github.luizgrp.sectionedrecyclerviewadapter:sectionedrecyclerviewadapter:1.0.4') {
        exclude group:'com.android.support', module:'appcompat-v7'
}
```

**Comment by lucas-dev** [comment]
Thanks again for the support luizgrp! Unfortunately, the proposed solution didn't fix the problem.
I'm attaching a screenshot of my Android Studio installation with the message from the gradle build.

![screenshot from 2016-10-12 20-24-24](https://cloud.githubusercontent.com/assets/7196515/19331238/f1ecea68-90b9-11e6-887c-279a7bc0724d.png)

I'll let you know if I find a solution.

**Comment by luizgrp** [comment]
ok, now it is complaining about recyclerview instead of appcompat, so try again with:
```
compile ('io.github.luizgrp.sectionedrecyclerviewadapter:sectionedrecyclerviewadapter:1.0.4') {
        exclude group:'com.android.support', module:'appcompat-v7'
        exclude group:'com.android.support', module:'recyclerview-v7'
}
```

**Comment by lucas-dev** [comment]
It's working now! Could you please explain what is going on here? I don't understand why the sectionedrecyclerviewadapter is conflicting with the appcompat and the recyclerview.

BTW, should I close this issue right now?

**Comment by ferfesh** [comment]
> I fixed the problem by manually adding the library files to my project

I am also facing the same problem
please
Can you tell me how to manually add it to your app?
