### ISSUE TITLE
Error build after implementing library version 2.1.0

### ISSUE THREAD

**Issue by MathiewNguyen** [luizgrp/SectionedRecyclerViewAdapter#170]
Dear Supporters,

I want to use this library on my project, but after I implementation the library version 2.1.0 as below:
 
**implementation 'io.github.luizgrp.sectionedrecyclerviewadapter:sectionedrecyclerviewadapter:2.1.0'**

Then I ran my project and I got an error:

:app:transformClassesWithMultidexlistForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> com.android.build.api.transform.TransformException: Error while generating the main dex list.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s

**This is my build tool of my project:**
`android {
  compileSdkVersion 28
  buildToolsVersion '28.0.3'
  defaultConfig {
    multiDexEnabled true
    minSdkVersion 19
    targetSdkVersion 26
  }`
**SectionedRecyclerViewAdapter library:**
 - Version: 2.1.0

Could you please help me to resolve this issue?

Thanks in advance.

**Comment by hdsrob** [comment]
Ran into the same error while adding this library to a new project. 

It's likely that the error is related to the use of Java 8: https://stackoverflow.com/questions/49512629/default-interface-methods-are-only-supported-starting-with-android-n

Changing Source and Target Compatibility fixed the issue for me.

**Comment by MathiewNguyen** [comment]
Hi Hdsrob,
Thanks for your comments. I solved it. But seem there is another issue.
I used this method, but seems it didn't work.
    new Handler().postDelayed(new Runnable() {
      @Override
      public void run() {
        mRecyclerView.scrollToPosition(position);
      }
    }, 300);
Di you meet this issue? and how to resolve it?
Thanks for your support.

**Comment by kaustav07** [comment]
I already have Java 8 Enabled in my projects but still get that same error on build, any solution yet?

**Comment by luizgrp** [comment]
@MathiewNguyen could you please open ask a question on [Stackoverflow](http://www.stackoverflow.com) providing more details, like what's the error you are getting?

@kaustav07 did you try the solution proposed by @hdsrob ?

**Comment by kaustav07** [comment]
@luizgrp I have already Java * enabled which was @hdsrob 's solution, but still it was not working, currently I am using version 1.2.0 of this library which is working fine.

**Comment by luizgrp** [comment]
@kaustav07 it's hard to give a solution with too little information about your project.
Could you please create a project from scratch and add the library and see if it works? 
If it doesn't could you please add to a repository in your github account and share with us? Please keep [this](https://stackoverflow.com/help/minimal-reproducible-example) in mind when creating it.
You can also check the demo app configurations, which is working with the current version of the library.
