### ISSUE TITLE
Is it possible to support Paging concept introduced in recent year?

### ISSUE THREAD

**Issue by yccheok** [luizgrp/SectionedRecyclerViewAdapter#176]
- [x] I have verified there are no duplicate open or recent questions.
- [x] I have read over the documentation, checked out the examples and the demo app.
- [x] I have given my issue a non-generic title.
- [x] I understand that if I ask the same question in [stackoverflow](http://www.stackoverflow.com) website I will get answers way faster as more people will try to answer it.
- [x] I understand that if I don't show a minimum effort of what I have tried and where I got stuck the question will be closed and marked as invalid.
- [x] I have read the article [How do I ask a good question?](https://stackoverflow.com/help/how-to-ask)
- [x] I understand that this library is a custom [Adapter](https://developer.android.com/reference/android/support/v7/widget/RecyclerView.Adapter.html) and **NOT** a custom [RecyclerView](https://developer.android.com/reference/android/support/v7/widget/RecyclerView.html). I understand the difference between them and what is possible to be done in an Adapter but not in a RecyclerView.

I really like the `addSection` concept provided by this library.

In recent year, Google introduced Paging concept. Instead of having to load entire data from database into memory, then present it in RecyclerView. User can now choose to only load a very small subset of data, during RecyclerView scrolling. 

Google achieves so by introducing
- https://developer.android.com/reference/android/arch/paging/PagedListAdapter
- `LiveData<PageList<...>>` returned by Room DB

The key concept, is to call `submitList` in `PagedListAdapter`, whenever the new subset of data is available, during scrolling.

A nice introduction video during Google I/O 2018 is available - https://www.youtube.com/watch?v=BE5bsyGGLf4

Currently, I cannot see a direct way, how we can fit such `submitList` paging concept, into `SectionedRecyclerViewAdapter`. 

I was wondering, do you have any idea how we can achieve Section concept, yet able to provide paging capability?

Thank you.

**Comment by yccheok** [comment]
After reading https://medium.com/@chibatching/how-to-connect-paging-library-with-groupie-f8b4102d59b0 and look at her example project (She is using a class called `Group`, which I believe is analogue to `Section`)

https://github.com/chibatching/paging-retrofit-sample/blob/master/app/src/main/java/com/chibatching/pagedlistgroup/PagedListGroup.java

I believe we can achieve similar effect, by having `PagedListSection`

I was wondering, whether you are interested to incorporate paging capability into your library? If yes, I'm more than happy, to spend some time to R&D, and provide proper implementation for such capability.

(Note, this may introduce `androidx.paging` dependency into your library)

Thank you!

**Comment by luizgrp** [comment]
Hey @yccheok , happy to have this introduced in the library, but please do any R&D on top of branch [3.0.0](https://github.com/luizgrp/SectionedRecyclerViewAdapter/tree/3.0.0) as I'm planning to have a new [release](https://github.com/luizgrp/SectionedRecyclerViewAdapter/milestone/6) soon.

**Comment by ahmadmssm** [comment]
@luizgrp Any thing new regarding this feature/request ?

**Comment by yccheok** [comment]
Sorry. I haven't look into this. This month and next month, I will kick start a new project which requires me to employ paging concept. Hopefully I can learn something new, and provide some useful input to this ticket.

**Comment by ahmadmssm** [comment]
@yccheok Thanks for your reply, I tired to implement it but no luck until now, I also need it in a project too.
