### ISSUE TITLE
Error adding to dependecies

### ISSUE THREAD

**Issue by alryan** [luizgrp/SectionedRecyclerViewAdapter#179]
ERROR: Failed to resolve: io.github.luizgrp.sectionedrecyclerviewadapter:sectionedrecyclerviewadapter:x.y.z
Show in Project Structure dialog
Affected Modules: app

How to solve this?

**Comment by luizgrp** [comment]
you should replace `x.y.z` by the latest version of the library, e.g.: 2.1.0
