### ISSUE TITLE
How can I get the Section header position?

### ISSUE THREAD

**Issue by rashidfiverivers** [luizgrp/SectionedRecyclerViewAdapter#185]
How can I get the Section header position?

**Comment by luizgrp** [comment]
Closing and marking as invalid as it's not using any of the templates.

**Comment by rashidfiverivers** [comment]
What does it mean by not using any templates?

**Comment by luizgrp** [comment]
when you push the "new issue" button, four buttons should be displayed with templates for the kind of issue that you are opening. in this case you should have used the "question" template

**Comment by rashidfiverivers** [comment]
Yes I did choose the "question" . Anything wrong?

**Comment by luizgrp** [comment]
yes, I don't see the the checkboxes from the [template](https://github.com/luizgrp/SectionedRecyclerViewAdapter/blob/master/.github/ISSUE_TEMPLATE/question.md) in the description of this issue
