### ISSUE TITLE
Suggestion to add example-code on how to use empty-views

### ISSUE THREAD

**Issue by haukesomm** [luizgrp/SectionedRecyclerViewAdapter#186]
The [code examples](https://github.com/luizgrp/SectionedRecyclerViewAdapter/tree/master/app/src/main/java/io/github/luizgrp/sectionedrecyclerviewadapter/demo) are lacking example-code on how to display an empty-view if the list is empty.  
It would be very useful for new users to have an example similar to the existing ones.

- [X] I understand that this library is a custom [Adapter](https://developer.android.com/reference/android/support/v7/widget/RecyclerView.Adapter.html) and **NOT** a custom [RecyclerView](https://developer.android.com/reference/android/support/v7/widget/RecyclerView.html). I understand the difference between them and what is possible to be done in an Adapter but not in a RecyclerView.

**Comment by luizgrp** [comment]
Addressed in https://github.com/luizgrp/SectionedRecyclerViewAdapter/pull/187

**Comment by luizgrp** [comment]
@haukesomm thanks for the suggestion 👍
