### ISSUE TITLE
How to get header position?

### ISSUE THREAD

**Issue by thinkgood2830** [luizgrp/SectionedRecyclerViewAdapter#191]
**Describe the bug**

**Expected behavior**

**Screenshots**

**SectionedRecyclerViewAdapter library:**
 - Version: [e.g. 1.2.0]

**Additional context**

**MVCE**
Please include a [minimal, complete, and verifiable example](https://stackoverflow.com/help/mcve)(MCVE) to help us identify the issue. This also helps check that the issue is not with your own code. The MCVE can be one of the following:
- Unit tests with the scenario where the issue happens;
- Modified [demo app](https://github.com/luizgrp/SectionedRecyclerViewAdapter/tree/918337f66321055c7621377e5f5254b9b8078e4c/app) with the scenario where the issue happens - please also provide the steps to reproduce the issue;
- Your own code including layouts;
- Link to the MCVE code/project:

**Comment by luizgrp** [comment]
```
sectionedAdapter.getAdapterForSection(section).getHeaderPosition()
```
