### ISSUE TITLE
Can we have SectionedRecyclerViewAdapter.getSectionItemViewTypeForAdapterViewType as static method?

### ISSUE THREAD

**Issue by yccheok** [luizgrp/SectionedRecyclerViewAdapter#198]
Can we have https://github.com/luizgrp/SectionedRecyclerViewAdapter/blob/master/library/src/main/java/io/github/luizgrp/sectionedrecyclerviewadapter/SectionedRecyclerViewAdapter.java#L500

as static method?

    public static int getSectionItemViewTypeForAdapterViewType(final int itemViewType) {
        return itemViewType % VIEW_TYPE_QTY;
    }

This is especially useful in the following use case (Drag and move)

    @Override
    public int getMovementFlags(RecyclerView recyclerView, RecyclerView.ViewHolder viewHolder) {
        if (SectionedRecyclerViewAdapter.VIEW_TYPE_ITEM_LOADED != SectionedRecyclerViewAdapter.getSectionItemViewTypeForAdapterViewType(viewHolder.getItemViewType())) {
            final int dragFlags = 0;
            final int swipeFlags = 0;
            return makeMovementFlags(dragFlags, swipeFlags);
        }

Thanks.

**Comment by luizgrp** [comment]
sure 👍

**Comment by yccheok** [comment]
Thank you. Didn't expect such a speedy response.
