### ISSUE TITLE
Section Position

### ISSUE THREAD

**Issue by EvlinLee** [luizgrp/SectionedRecyclerViewAdapter#24]
Hi, how can i set the position of section?

**Comment by luizgrp** [comment]
The sections are displayed in the order that they were added to the adapter.
Please see this [example](https://github.com/luizgrp/SectionedRecyclerViewAdapter/blob/master/app/src/main/java/io/github/luizgrp/sectionedrecyclerviewadapter/demo/Example2Fragment.java#L34-L37).
