### ISSUE TITLE
Divider drawn between items in StatelessSection

### ISSUE THREAD

**Issue by Nutomic** [luizgrp/SectionedRecyclerViewAdapter#25]
I'm adding a seperator to my RecyclerView with this code:
```
DividerItemDecoration dividerItemDecoration = new DividerItemDecoration(recyclerView.getContext(),
    layoutManager.getOrientation());
recyclerView.addItemDecoration(dividerItemDecoration);
```

However, the divider is also drawn between items in a section. You can see this in the screenshot (I changed the color to red for better visibility). Dividers should only be visible above "TechRabbit" and "Amazon.com".
![screenshot_20161223-102857](https://cloud.githubusercontent.com/assets/1044450/21445355/4a118ce8-c8fb-11e6-86c1-91d746cd536e.png)

I'm happy to help with this, if you tell me how it can be fixed.

**Comment by luizgrp** [comment]
Unfortunately this is how RecyclerView works, this library it's only a custom adapter not a custom RecyclerView.

If you don't want the lines for every item, don't use ItemDecoration and add the line in your header layout as in many examples of the [demo](https://github.com/luizgrp/SectionedRecyclerViewAdapter/blob/master/app) app, for instance, check the header [layout](https://github.com/luizgrp/SectionedRecyclerViewAdapter/blob/master/app/src/main/res/layout/section_ex1_header.xml#L21) of [Example1](https://github.com/luizgrp/SectionedRecyclerViewAdapter/blob/master/app/src/main/java/io/github/luizgrp/sectionedrecyclerviewadapter/demo/Example1Fragment.java).
