### ISSUE TITLE
could i setting  StatelessSection ?

### ISSUE THREAD

**Issue by stephen-niu** [luizgrp/SectionedRecyclerViewAdapter#27]
hi you project was wonderful,but i need some special
look this image 
<img width="551" alt="d06166e5-1640-4816-98c3-7d8d3ee8c85f" src="https://cloud.githubusercontent.com/assets/17307584/21603342/890bbef2-d1d7-11e6-9719-71c97c8ad021.png">
 for this view   i need add two section
SectionedRecyclerViewAdapter.addSection(new AnchorListSection())
SectionedRecyclerViewAdapter.addSection(new LiveListSection())
but  the part of 2   i need setting two line   so  that's  the problem
SectionedRecyclerViewAdapter only  can setting  unitive  line
but  i need setting the  item line 
i think StatelessSection should offer  some  API   that i can setting  each item line

**Comment by luizgrp** [comment]
Hi, please try adding the line to your item's layout as it's done [here](https://github.com/luizgrp/SectionedRecyclerViewAdapter/blob/master/app/src/main/res/layout/section_ex1_header.xml#L21).
