### ISSUE TITLE
Multiple view type

### ISSUE THREAD

**Issue by Dule95D** [luizgrp/SectionedRecyclerViewAdapter#31]
Is it possible to use `getItemViewType` with this library?

**Comment by luizgrp** [comment]
Yes, but I would suggest to use [getSectionItemViewType ](https://github.com/luizgrp/SectionedRecyclerViewAdapter/blob/c0896d4449ee14eb1a4da23cc93c36738154bc48/library/src/main/java/io/github/luizgrp/sectionedrecyclerviewadapter/SectionedRecyclerViewAdapter.java#L299) instead, check it out!

**Comment by ViTVetal** [comment]
@luizgrp I tried use getItemViewType but get cast problems (my itemViewHolder to Header). I cannot use separate view types for header and footer. Because on the grid layout, the footer will be displayed as an item

**Comment by luizgrp** [comment]
Hi @ViTVetal, if in your project you have to display the footer as an item then you will have to code your own "getSectionItemViewType" to distinguish an item from a footer
