### ISSUE TITLE
Add decoration for sections only

### ISSUE THREAD

**Issue by markkko** [luizgrp/SectionedRecyclerViewAdapter#38]
Is it possible to add Item decoration but just to separate sections, not items?

**Comment by luizgrp** [comment]
Hi @markkko,

What have you tried so far? Where did you get stuck?

This article explains how to do it, check out the topic "Don’t add dividers as views — It lacks flexibility": https://medium.com/proandroiddev/itemdecoration-in-android-e18a0692d848

In the example it explains how to get the [adapterPosition](https://gist.github.com/DevAhamed/6b28bfdc0dc46e85fc29c8df8718ac6b#file-itemdecoration-java-L10). Then where it checks for the [lastPosition](https://gist.github.com/DevAhamed/6b28bfdc0dc46e85fc29c8df8718ac6b#file-itemdecoration-java-L11) you can use the library method [getSectionItemViewType](https://github.com/luizgrp/SectionedRecyclerViewAdapter/blob/5ed2a2a1530a87bd7b4f23f2547791a2de15afd2/library/src/main/java/io/github/luizgrp/sectionedrecyclerviewadapter/SectionedRecyclerViewAdapter.java#L309) to check if it's the footer. If your section doesn't have footer you can check if it's the last item using [getPositionInSection](https://github.com/luizgrp/SectionedRecyclerViewAdapter/blob/5ed2a2a1530a87bd7b4f23f2547791a2de15afd2/library/src/main/java/io/github/luizgrp/sectionedrecyclerviewadapter/SectionedRecyclerViewAdapter.java#L358) and [getSectionItemsTotal](https://github.com/luizgrp/SectionedRecyclerViewAdapter/blob/5ed2a2a1530a87bd7b4f23f2547791a2de15afd2/library/src/main/java/io/github/luizgrp/sectionedrecyclerviewadapter/Section.java#L207).

Hope it helps.
