### ISSUE TITLE
Is it possible to have EMPTY in Section class

### ISSUE THREAD

**Issue by yccheok** [luizgrp/SectionedRecyclerViewAdapter#39]
Currently, in `Section` class, we have

    public enum State { LOADING, LOADED, FAILED}

Is it possible to support

    public enum State { LOADING, LOADED, FAILED, EMPTY}

This is because sometimes, the data within a section is empty, we need to show different UI.

Thanks for the very thoughtful library. It saves developers a lot of time.

**Comment by yccheok** [comment]
Hi, I had modified the code, to support EMPTY state.

https://github.com/luizgrp/SectionedRecyclerViewAdapter/pull/41

Hope you will find it is useful. I had added 2 more unit tests, for this new feature.

**Comment by luizgrp** [comment]
Hi @yccheok, many thanks for you pull request, I will review it soon! 👍

**Comment by yccheok** [comment]
Thanks @luizgrp 

Last few weeks, I also made 2 more modifications on the library for the following purpose

1. Added `getAdapterPosition`. Sometimes, I find it is useful, to programmatically scroll the Recycler View to the newly added item. In that case, for a given position relative to section, I need to convert it to absolute position (I call it as adapter position)

My use case is as follow :

    String iso3 = createLiveAccount.getCountryID();
    // Returns position relative to Section.
    int position = countryCitizenshipSection.getPosition(iso3);
    if (position < 0) {
        return;
    }
    int adapterPosition = sectionAdapter.getAdapterPosition(countryCitizenshipSection, position);
    Utils.scrollIfNecessary(recyclerView, adapterPosition);
    
    public static void scrollIfNecessary(RecyclerView recyclerView, int position) {
        LinearLayoutManager layoutManager = (LinearLayoutManager) recyclerView.getLayoutManager();
        if (position < layoutManager.findFirstCompletelyVisibleItemPosition() || position > layoutManager.findLastCompletelyVisibleItemPosition()) {
            layoutManager.scrollToPositionWithOffset(position, 0);
        }
    }

Another use case it, when notify adapter with delete/ update/ insert/ ... , the previous API requires "TAG for section". However, I find it sometime it is difficult to caller to keep track TAG for section manually. Hence, instead of accepting TAG only, I provide another version of methods, to accept Section as method parameter.

For instance, I expand 

    public void notifyItemInsertedInSection(String tag, int position)

to

    public void notifyItemInsertedInSection(Section section, int position)

Let me know if you like the 2 changes

https://github.com/yccheok/SectionedRecyclerViewAdapter/commits/master

I'm happy to send you a pull request.

Thanks.

**Comment by luizgrp** [comment]
PR #51
