### ISSUE TITLE
Does it make sense to provide setItemResourceId for Section class

### ISSUE THREAD

**Issue by yccheok** [luizgrp/SectionedRecyclerViewAdapter#45]
Currently, I have a use case.

The content of item, will based on network result from server. Its code more or less look as the following.

    watchlistSection.setState(Section.State.LOADING);
    ...
    ...
    // Perform some networking operation, to return user current status.
    ...
    ...
    watchlistSection.setItemResourceId(getBestItemResourceIdBasedNetworkingOperationResult());
    watchlistSection.setState(Section.State.LOADED);

Currently, the only way to provide item resource id for `Section`, is via constructor. We do not have `setItemResourceId`.

Does it make sense to add the following code in `Section` ?

    // Section.java
    public void setItemResourceId(int itemResourceId) {
        this.itemResourceId = itemResourceId;
    }

**Comment by luizgrp** [comment]
Hi @yccheok,

Having the `setItemResourceId` will lead people to think that they can change the layout of the item dynamically. Changing the layout of the items before having any items displayed on the RecyclerView is fine, the problem is changing after items are displayed, the RecyclerView will send the old ViewHolder to the onBindViewHolder method. 

I think this is related to #9. Do you think their suggestion would work for your scenario?

**Comment by yccheok** [comment]
Do you mean that, for #9, we need to modify `Section` class, to have the following abstract methods (or non abstract but designed to be override-able)?

    public abstract RecyclerView.ViewHolder getItemViewHolder(View view, int viewType)
    public abstract int getItemViewType(int position)

Or, to reduce burden of developer to implement abstract method, the 2 new methods come with default implementation

    public RecyclerView.ViewHolder getItemViewHolder(View view, int viewType) {
        return getItemViewHolder(view);
    }

    public int getItemViewType(int position) {
        return 0;
    }

**Comment by luizgrp** [comment]
Hey, just a follow up on this:

> Is it possible to still have setItemResourceId in Section, but throw run-time exception, if layout has been inflated?

Yes, it would be possible and it sounds like a simple idea. 
However it wouldn't be a solution for the request in #9. I would like to put this on hold until we define a solution that could potentially be used for both. If we find out that there is no good solution to attend both then we go forward with this.

I also liked your proposal for for #9 and I agree with your statement that will add complexity and discourage adoption. Maybe we could create a separate ComplexItemsSection class with those capabilities and keep the old Section and StatelessSection alone?

What do you think of the proposed solution by @percula in #9?

**Comment by yccheok** [comment]
@luizgrp Currently, I tackle my use case using current production library. What I did is I still use a single loaded resource id. However, in my loaded resource, it contains multiple views. I just turn on/ turn off the view during run-time, based on network result. 

I'm interested in looking into @percula #9. I will spend some time to look into it, and provide feedback if I have any.

**Comment by luizgrp** [comment]
Thanks for the follow up, that's the way it should be in my opinion 👍
