### ISSUE TITLE
Does it make sense to provide notifyItemChangedInHeader and notifyItemChangedInFooter

### ISSUE THREAD

**Issue by yccheok** [luizgrp/SectionedRecyclerViewAdapter#47]
I was wondering, does it make sense, to provide the following methods

    notifyItemChangedInHeader(String TAG)
    notifyItemChangedInHeader(Section section)
    notifyItemChangedInFooter(String TAG)
    notifyItemChangedInFooter(Section section)

Currently, I have the following use case.

![small](https://user-images.githubusercontent.com/308276/27466337-6db77d42-580c-11e7-989b-535317abe062.png)

For the following 3 components, they are belongs to single item in single section

- price (968.99) as same Item within same Section
- chart as same Item within same Section
- buttons (buy & sell) as same Item within same Section

So, whenever there are changes in `price` or `buttons`, I need to call `notifyItemChangedInItem`. However, chart drawing is an expensive activity. Calling `notifyItemChangedInItem` will cause unnecessary chart re-drawing. My current workaround is to keep a special position flag, to prevent unnecessary chart re-drawing.

My ideal way is to place

- price (968.99) as Header within same Section
- chart as Item within same Section
- buttons (buy & sell) as Footer within same Section

So, whenever there are changes in `price` or `buttons`, I just need to call `notifyItemChangedInHeader` or `notifyItemChangedInFooter`, without trigger chart as item.

If such changes make sense, I'm more to happy to send another pull request for that.

Thank you.

**Comment by shuwnyuantee** [comment]
👍

**Comment by luizgrp** [comment]
They do make sense to me, please go on and submit a pull request 👍 

By `notifyItemChangedInItem` you mean [notifyItemChangedInSection](https://github.com/luizgrp/SectionedRecyclerViewAdapter/blob/c4535f5419b0aa19cc27118eff4f201a58dac1c9/library/src/main/java/io/github/luizgrp/sectionedrecyclerviewadapter/SectionedRecyclerViewAdapter.java#L585)?

I just don't understand why when you call `notifyItemChangedInSection` for item 1 (price) or 3 (buttons) is making item 2 (chart) to redraw?

**Comment by yccheok** [comment]
Sorry for confusion. I mean `notifyItemChangedInSection`.

The "price", "buttons" and "chart" are all belong to single item, in that single section. That single section only contain 1 item at this moment.

**Comment by luizgrp** [comment]
It makes sense now, sorry, the confusion was my bad!

**Comment by yccheok** [comment]
Hi, I had submitted PR for https://github.com/luizgrp/SectionedRecyclerViewAdapter/pull/52

Hope you will like it :)

**Comment by yccheok** [comment]
@luizgrp 

Sorry for asking. I'm not trying to rush you on this. I just would like to know, do you have any estimation time, on when this PR will be reviewed, and then released to master?

Then reason is that, currently, we are using a forked version of this great library, in our production project. However, our forked version still lack of this `notifyItemChangedInHeader` and `notifyItemChangedInFooter`.

We don't feel comfortable to relying on forked version lib. We still prefer to stick back to original master, once this is being merged to master (Along with builder feature, empty view feature, Section as method parameter)

Thank you :)

**Comment by luizgrp** [comment]
Hey @yccheok, no problem at all in asking!

I only need to review the unit tests of that PR to get it merged. 

Then I have to do few bits in order to release a new version:
- Update lib version;
- Update CHANGELOG;
- Update README with new state and version;
- Update demo app with a sample of the empty state (not a blocker);
- Update README with screenshot of demo app with EMPTY state (not a blocker);

I'm not available to work on it this weekend, I will try my best to have a release on Fri but Mon would be a safer date to say. Would that be OK for you?

**Comment by yccheok** [comment]
@luizgrp 

Thanks you very much for the info! I will then look forward for the Mon release.

**Comment by luizgrp** [comment]
@yccheok v1.1.0 released 👍

**Comment by yccheok** [comment]
@luizgrp Oh my. Thank. Hotly fresh baked code. Going to try it out now...

**Comment by yccheok** [comment]
@luizgrp Sorry. I think I introduce a bug for the EMPTY state feature.

https://github.com/luizgrp/SectionedRecyclerViewAdapter/pull/54

Can you kindly merge again.
