### ISSUE TITLE
Horizontal Scroll possible?

### ISSUE THREAD

**Issue by trinadhkoya** [luizgrp/SectionedRecyclerViewAdapter#48]
How to make horizontal Scrollable ??i tried making Linear LAyout Manager as Horizontal.It doesnot look good

**Comment by luizgrp** [comment]
Hi, could you please show the code and give better explanation of what does not look good?

**Comment by trinadhkoya** [comment]
I want it to be like play store mode !! I am talkin about stateless fragment !!  So I changed the orientation to Horizonatal ,then it looks bad

**Comment by luizgrp** [comment]
Linked to #44

**Comment by RowlandOti** [comment]
The problem now is there will be no call to `notifyDatasetChanged()` or other similar methods for such a nested structure. The view won't be able to update in some cases when data is sent late or  recyclerview si start with **wrap_content.**
