### ISSUE TITLE
How can I call notifyItemChanged from within StatelessSection?

### ISSUE THREAD

**Issue by aaronwardle** [luizgrp/SectionedRecyclerViewAdapter#55]
Hi, 

First of all thanks for the section recycler view adapter it works very well. 

We are now trying to implement swipe to delete feature and I am struggling in figuring out how we can call **notifyItemChangedInSection** from within our custom class which extends the StatelessSection?

Thanks in advance.

**Comment by luizgrp** [comment]
Hi @aaronwardle, glad to hear it's working well for you :)

Please have a look at example [4](https://github.com/luizgrp/SectionedRecyclerViewAdapter/blob/27213a5da54647593e842bad8ad02908413f2b28/app/src/main/java/io/github/luizgrp/sectionedrecyclerviewadapter/demo/Example4Fragment.java#L130), it's calling **notifyDataSetChanged** from within a custom class which extends StatelessSection.

You can probably do the same?

**Comment by aaronwardle** [comment]
Hi

Thats great will try it out :) 

Thanks for the quick reply

**Comment by robert-00** [comment]
Hi  luizgrp  but the  example 4, calls `notifyDataSetChanged` inside the `StatelessSection`. 

I have same iusse.  Calling `notifyDataSetChanged` outside `StatelessSection` have no effect.

ps_ sorry for double post.
