### ISSUE TITLE
not really an issue more like a concern

### ISSUE THREAD

**Issue by Scorlin** [luizgrp/SectionedRecyclerViewAdapter#59]
hey this is not really an issue more like a concern.. what are the chances that you stop updating this library in the future i dont want to use it and then it breaks later down the road

**Comment by luizgrp** [comment]
I guess the same chances as for any open source library that is not maintained by a company.
If you are looking for a similar library backed by a company you could try [epoxy](https://github.com/airbnb/epoxy) or [graywater](https://github.com/tumblr/graywater) 👍

**Comment by yccheok** [comment]
@luizgrp 
Thanks for sharing the above 2 libs. I didn't know about it.

@Scorlin 
I can share my experience of using this lib in my production app, for several months.

1. This lib acts as a very thin extra layer, on the top of existing `RecyclerView` adapter. No new architecture or new concept were introduced. Hence, it is very easy to use.

2. The code logic is very straightforward, and easy to understand. Hence, I do have a high confident level, on the bugfree level of this lib.

3. It comes with a comprehensive set of unit tests. Hence, even when @luizgrp no longer maintain it, you still can easily modify the code, with less worry of breaking existing behavior.
