### ISSUE TITLE
Change State of Section using notifyItemChangedInSection will cause unwanted animation

### ISSUE THREAD

**Issue by yccheok** [luizgrp/SectionedRecyclerViewAdapter#62]
Currently, if I change the Section's State via

    // Current State is FAILED.        
    watchlistSection.setState(Section.State.LOADING);
    sectionAdapter.notifyItemChangedInSection(watchlistSection, 0);

It will cause unwanted animation. Although I had tried to turn off animation via

    RecyclerView.ItemAnimator itemAnimator = this.recyclerView.getItemAnimator();
    if (itemAnimator instanceof SimpleItemAnimator) {
        ((SimpleItemAnimator)itemAnimator).setSupportsChangeAnimations(false);
    }

It doesn't help much. As you can see in the video, when the View changed from 

a sad cloud face to progress bar

, there's unwanted flickering effect.

https://youtu.be/x-X-SXs0Acc - Using setSupportsChangeAnimations(false)

Note, if I use the following code, there's still a unwanted flickering effect. But, this time, the flickering effect is different from previous

    RecyclerView.ItemAnimator itemAnimator = this.recyclerView.getItemAnimator();
    if (itemAnimator instanceof SimpleItemAnimator) {
        ((SimpleItemAnimator)itemAnimator).setSupportsChangeAnimations(true);
    }

https://youtu.be/m4jLfhUpjQc - setSupportsChangeAnimations(true)

I can completely eliminated the unwanted flickering effect, by removing SimpleItemAnimation. However, this will cause other problem. Some, some item in the recycler view, I need to perform swipe-to-delete and drag-n-move UX effect. Without SimpleItemAnimation, I can't achieve such effect.

    this.recyclerView.setItemAnimator(null);

https://youtu.be/MyZlqPCeS7s - this.recyclerView.setItemAnimator(null)

Any idea how I can avoid unwanted animation/ flickering effect during notifyItemChangedInSection, without removing `SimpleItemAnimation`? I expect `setSupportsChangeAnimations(false)` will work, but it doesn't.

**Comment by yccheok** [comment]
Long time ago, I'm facing a similar issue when using `notifyDataSetChanged`.

https://stackoverflow.com/questions/33851370/applying-statelistanimator-in-recylerviews-item-will-cause-flickering-effect-wh

Last time, I solve it using stable id. This time, I'm not sure I was able to solve using stable id. Not sure how to generate stable id for Section Item, and Section EMPTY, LOADING, ...

**Comment by yccheok** [comment]
I did a quick testing using

        sectionAdapter = new SectionedRecyclerViewAdapter() {
            @Override
            public long getItemId(int position) {
                return position;
            }
        };

        sectionAdapter.setHasStableIds(true);

However, the flickering still happen. Maybe I didn't implement `getItemId` correctly?

**Comment by luizgrp** [comment]
would you be able to reproduce it in the demo app? 
if so could you please create a branch in your fork so I can investigate it?

**Comment by luizgrp** [comment]
@yccheok have you managed to fix this issue?

Most of the examples of the demo app were updated and calls to notify* were added, I didn't see any similar issue. The call to notifyItemChanged is being made in example 9 (payloads).

**Comment by yccheok** [comment]
Thanks. Is a 2 years old problem :)

I re-check the code back. I think my workaround is to

```
this.itemAnimator = this.recyclerView.getItemAnimator();
this.recyclerView.setItemAnimator(null);
```

Before calling `notifyItemChangedInSection`

Whenever I need animation (Like drag and move), I just restore back the `this.itemAnimator` to `this.recyclerView`

Such workaround works good for me, although the code has became cumbersome.
