### ISSUE TITLE
how to add click effect when i click on item on a section?

### ISSUE THREAD

**Issue by ahmedsaber00** [luizgrp/SectionedRecyclerViewAdapter#63]
when i click on an item , it fire the click listener correctly but i need effect on the item also
how can i do this ?

**Comment by luizgrp** [comment]
Hi, what have you tried so far and where did you get stuck?

**Comment by evatheodoridoubjss** [comment]
Hi, I have a similar problem. 

I have used your sectionedrecyclerviewadapter with multiple cardviews inside that are being populated from a database.

I have tried implementing my own RecyclerView.OnItemTouchListener and overriding the onInterceptTouchEvent method, but that has no effect when I click on an item.

Do you provide an implementation for it or have any suggestions for how to implement it?
