### ISSUE TITLE
Question: Any plan for implement sticky headers with sections?

### ISSUE THREAD

**Issue by Diego-Franco** [luizgrp/SectionedRecyclerViewAdapter#7]
you have a good job with this library, but in some point do you have any plan for work with sticky headers? 

this will be a great library if you add this part, i'll try to add to if you want some help

**Comment by luizgrp** [comment]
Hi @Diego-Franco, thanks for your comment! 
Yes, I'm planning to work on sticky headers soon and help is always welcome, it would be great if you could contribute :)

**Comment by jeffdgr8** [comment]
For anyone looking for a solution for sticky headers, it was really easy to implement using this library: https://github.com/bgogetap/StickyHeaders

I wrote a small class which enables utilizing together with this library: https://gist.github.com/jeffdgr8/61a4c6432401bf2740cd17cd04f7ee4e
