### ISSUE TITLE
Header position for horizontal orientation

### ISSUE THREAD

**Issue by abhishek-jacob** [luizgrp/SectionedRecyclerViewAdapter#73]
I was trying to set up a Recyclerview with Horizontal orientation `(LinearLayoutManager.HORIZONTAL)`. The header is displayed on the left side of the list. Is there an option to make it appear on the top of the list?

**Comment by luizgrp** [comment]
It's all down to the way you build your layout, your RecyclerView can have a vertical orientation and the items of this vertical RecyclerView can have a RecyclerView with horizontal orientation in it?

You can also try [library](https://github.com/rubensousa/RecyclerViewSnap).
