### ISSUE TITLE
how to remove section if i removed all items inside it ?

### ISSUE THREAD

**Issue by ahmedsaber00** [luizgrp/SectionedRecyclerViewAdapter#74]
iam tring to remove section after removing all items inside it but i can't
i tried this line 
    if (section.getContentItemsTotal()==0)
                                sectionAdapter.removeSection(String.valueOf(sectionTag));
but it crash with that error 

java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{532fa4d4 position=11 id=-1, oldPos=12, pLpos:12 scrap [attachedScrap] tmpDetached no parent}

what should i do if i want to delete a section ?

**Comment by luizgrp** [comment]
Have you tried the solutions proposed [here](https://stackoverflow.com/a/33822747/1401164)? It looks like there is bug in the RecyclerView as per [here](https://issuetracker.google.com/issues/37007605#c10).
