### ISSUE TITLE
How can I add pagination to a section ? if my lists for each section is coming from a different network call ?

### ISSUE THREAD

**Issue by Janipasha** [luizgrp/SectionedRecyclerViewAdapter#76]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests.
- [x] I have verified that I am using the latest version of SectionedRecyclerViewAdapter.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation, checked out the examples and the demo app (before asking questions on how to do something).

###### Include the following:
 - SectionedRecyclerViewAdapter version: `0.x.x`
 - Device OS version: `7.1.1`
 - Device Manufacturer: `Google`
 - Device Name: `Pixel XL`

Also, please wrap Java with correct syntax highlighting.

```java
System.out.println("Hello, world!");
```
 
###### Reproduction Steps

1. 
2. 
3.

**Comment by luizgrp** [comment]
please open a question in stackoverflow with the tag [sectionedrecyclerviewadapter](https://stackoverflow.com/tags/sectionedrecyclerviewadapter) sharing the code that you have tried and explaining where you got stuck
