### ISSUE TITLE
How I can load more list and visible the fist item of next page  

### ISSUE THREAD

**Issue by Quoc-DEV** [luizgrp/SectionedRecyclerViewAdapter#77]
I used the `notifyItemChangedInSection` but when I load more next page the list scroll to the fist item of page 1! 
I want when i load more I keep scroll and show the fist item of page two ?

Sorry my english not good !

**Comment by luizgrp** [comment]
you can use the method [smoothScrollToPosition](
https://developer.android.com/reference/android/support/v7/widget/RecyclerView.html#smoothScrollToPosition(int)) from the RecyclerView.

you can see it being used in [Example8](https://github.com/luizgrp/SectionedRecyclerViewAdapter/blob/918337f66321055c7621377e5f5254b9b8078e4c/app/src/main/java/io/github/luizgrp/sectionedrecyclerviewadapter/demo/Example8Fragment.java#L94)

**Comment by marconealberto** [comment]
I tried following your example using tags, but the smoothScrollToPosition doesn't scroll the expandable header to the top of the window.

This is the code I use:

```
int sectionPos = sectionAdapter.getSectionPosition(tag);
myList.smoothScrollToPosition(sectionPos);
// the section is expandable
sectionAdapter.notifyDataSetChanged();
```
