### ISSUE TITLE
how to manage empty span in GridLayoutManager 

### ISSUE THREAD

**Issue by ZeroCool00** [luizgrp/SectionedRecyclerViewAdapter#79]
First of all thank you for this beautiful library.

section header is set as item if span is empty in GridLayoutManager, how do i solve this:

full description is here: 
 https://stackoverflow.com/questions/45931337/how-to-manage-empty-span-in-gridlayoutmanager

**Comment by dimaselpiojo** [comment]
My problem is the same. when i change spanCount 3
`GridLayoutManager glm = new GridLayoutManager(getContext(), 3);`
It's not working as I expected.

**Comment by ZeroCool00** [comment]
i'll add bounty tomorrow.. keep looking to my question, hope you can solve it too.

**Comment by AshishPsaini** [comment]
getting same issue

**Comment by AshishPsaini** [comment]
GridLayoutManager glm = new GridLayoutManager(getContext(),3);
        glm.setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {
            @Override
            public int getSpanSize(int position) {
                switch(sectionAdapter.getSectionItemViewType(position)) {
                    case SectionedRecyclerViewAdapter.VIEW_TYPE_HEADER:
                        return 3;
                    default:
                        return 1;
                }
            }
        });
this is working fine.

**Comment by luizgrp** [comment]
I replied to your stackoverflow thread, it seems to be working fine.

if anyone else is still having problems related to this please reply there sharing your code or open another question with the tag [sectionedrecyclerviewadapter](https://stackoverflow.com/tags/sectionedrecyclerviewadapter)
