### ISSUE TITLE
I want to add header & footer to recyclerview,not the sectional header.Is there any provision to do that with the provided SectionedRecyclerViewAdapter

### ISSUE THREAD

**Issue by TejshreeYeole** [luizgrp/SectionedRecyclerViewAdapter#81]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests.
- [x] I have verified that I am using the latest version of SectionedRecyclerViewAdapter.
- [ ] I have given my issue a non-generic title.
- [x] I have read over the documentation, checked out the examples and the demo app (before asking questions on how to do something).

###### Include the following:
 - SectionedRecyclerViewAdapter version: `0.x.x`
 - Device OS version: `7.1.1`
 - Device Manufacturer: `Google`
 - Device Name: `Pixel XL`

Also, please wrap Java with correct syntax highlighting.

```java
System.out.println("Hello, world!");
```
 
###### Reproduction Steps

1. 
2. 
3.

**Comment by luizgrp** [comment]
I'm afraid there is nothing out of the box, this library is a custom adapter not a custom recyclerview
