### ISSUE TITLE
Dependency not compiled   

### ISSUE THREAD

**Issue by lokeshkondaparthi** [luizgrp/SectionedRecyclerViewAdapter#83]
I got struct-ed while compiling library from Android Studio. 

Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.0.0-alpha1) from [com.android.support:appcompat-v7:26.0.0-alpha1] AndroidManifest.xml:27:9-38
	is also present at [com.android.support:recyclerview-v7:25.3.1] AndroidManifest.xml:24:9-31 value=(25.3.1).
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:25:5-27:41 to override.

**Comment by luizgrp** [comment]
Have you tried the suggestion? What was the result?
