### ISSUE TITLE
notifyDataSetChanged() has no effect outside StatelessSection

### ISSUE THREAD

**Issue by robert-00** [luizgrp/SectionedRecyclerViewAdapter#85]
Hi,
I'm trying example 5

I try to update the list out of class `public class MovieSection extends StatelessSection`

notifyDataSetChanged() has no effect.

only inside the class works.

How do you do it outside ?

I've looked at all the examples, but they all make   calling `notifyDataSetChanged()` inside the class.

Thanks

**Comment by luizgrp** [comment]
Not sure if that matters but [here](https://github.com/luizgrp/SectionedRecyclerViewAdapter/blob/918337f66321055c7621377e5f5254b9b8078e4c/app/src/main/java/io/github/luizgrp/sectionedrecyclerviewadapter/demo/Example6Fragment.java#L160) and [here](https://github.com/luizgrp/SectionedRecyclerViewAdapter/blob/918337f66321055c7621377e5f5254b9b8078e4c/app/src/main/java/io/github/luizgrp/sectionedrecyclerviewadapter/demo/Example4Fragment.java#L133) it's being called inside the Section class.
