### ISSUE TITLE
Dpad implementation

### ISSUE THREAD

**Issue by erenbakac** [luizgrp/SectionedRecyclerViewAdapter#87]
Hello,
Do you have  any plan about adding DPAD support to your library? Actually it works in the middle of rows. But first  and last item of rows doesnt jump to another row.Focus changes onto another view apart from list item.

**Comment by luizgrp** [comment]
Hey there,
I'm afraid not, this library is a custom adapter and not a custom recyclerview.
Have you tried the solution proposed [here](https://stackoverflow.com/questions/36887573/recyclerview-and-d-pad-navigation) or this [library](https://github.com/vganin/dpad-aware-recycler-view)?

**Comment by erenbakac** [comment]
İ will check them. Thank you for this great library....
