### ISSUE TITLE
What does 'VIEW_TYPE_QTY' mean?...count of VIEW_TYPE?

### ISSUE THREAD

**Issue by FreeLoopC** [luizgrp/SectionedRecyclerViewAdapter#89]
What does 'VIEW_TYPE_QTY' mean?...count of VIEW_TYPE?
Sorry. I just not understand QTY means what, Can you explain it please?
Another, I suggest you should add Comments in some Const Value

**Comment by luizgrp** [comment]
Hey, thanks for your suggestion.

QTY is a common abbreviation for "quantity".
VIEW_TYPE_QTY = quantity of view items in the adapter
