### ISSUE TITLE
Unable to remove first section from recyclerview

### ISSUE THREAD

**Issue by ajaykumarpprajapati** [luizgrp/SectionedRecyclerViewAdapter#94]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests.
- [x] I have verified that I am using the latest version of SectionedRecyclerViewAdapter.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation, checked out the examples and the demo app (before asking questions on how to do something).

###### Include the following:
 - SectionedRecyclerViewAdapter version: `0.x.x`
 - Device OS version: `7.1.1`
 - Device Manufacturer: `Google`
 - Device Name: `Pixel XL`

Also, please wrap Java with correct syntax highlighting.

```java
System.out.println("Hello, world!");
```
 
###### Reproduction Steps

1. 
2. 
3.

**Comment by ajaykumarpprajapati** [comment]
Tried lot even keeping visibility gone for 1st section in Recyclerview still not able to remove

**Comment by luizgrp** [comment]
Have you tried calling [notifyDataSetChanged](https://developer.android.com/reference/android/support/v7/widget/RecyclerView.Adapter.html#notifyDataSetChanged())?
